apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical-apps
value: 1000000
globalDefault: false
description: "Dla krytycznych usług e-commerce."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: background-tasks
value: 1000
globalDefault: false
description: "Dla zadań o niskim priorytecie."