apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - default: # Domyślny limit
      cpu: 500m
      memory: 512Mi
    defaultRequest: # Domyślna gwarancja
      cpu: 100m
      memory: 256Mi
    type: Container